# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: sistema_tj_development

test:
  <<: *default
  database: sistema_tj_test

production:
  <<: *default
  database: sistema_tj_production
